### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by hitesh4** [mozilla/sign-addon#219]
Had been trying to run it in console. Get this error attaching the screenshot, Need help me figure it out.
![screenshot from 2016-10-15 09-47-08](https://cloud.githubusercontent.com/assets/12246432/19407328/942211c4-92bc-11e6-8695-ae7e6a034a88.png)

**Comment by kumar303** [comment]
Hi. Sorry for the confusion. This module is written in newer ES6 syntax so it requires compilation to run in Node.

If you want to use the package locally (rather than installing it), you'll need to use the [development installation instructions](https://github.com/mozilla/sign-addon#development). This should get you what you need:
````
npm install
npm run build
node
> var sign = require('./dist/sign-addon').default;
> sign();
````
